################################################################################
# GNUmakefile for the physics list subsystem
#
# Change log:
# 18 March 2009 - Initial submission (Kareem)
#
################################################################################

name := physicslist

include ../LUXSimConfig/Libraries.gmk
