################################################################################
# example macro for the LUXSim package
#
# Change log:
# 10 Oct 2009 - Initial submission copied from example.mac (Melinda)
# 10-Oct-2009 - Changed to have LUX1_0 detector names only and added
#				cryoStand and gridWires example usage. (Melinda)
# 05-Mar-2010 - Changed gridWires command to off (Melinda)
# 25-Aug-2011 - Added source for p-Lithium neutron generator (Mike)
################################################################################

/run/verbose 0
/control/verbose 0
/tracking/verbose 0
/grdm/verbose 0
/process/verbose 0

#	This next set of lines is to, as it appears, initialize the simulation
/run/initialize

#	Next are the LUXSim-specific commands

#	Set the output directory
/LUXSim/io/outputDir ./

#	Select the kind of detector to use
/LUXSim/detector/select 1_0Detector

#	Set the muon veto (a.k.a. the water shield) on or off
#/LUXSim/detector/muonVeto on

#	Set the cryostat stand on or off (not fully developed)
#/LUXSim/detector/cryoStand on

#   Set the level of grid wires:
# wires makes individual wires inside a grid frame (optical)
# plane places a thin sheet inside the grid frame rather than wires (background)
# off places nothing
/LUXSim/detector/gridWires off 

#  Set the value of the Electric Field in Liquid and Gas Xenon 
#    Material Properties.  Use volt/cm or kV/cm to specify.
/LUXSim/detector/gasField 10 kV/cm
/LUXSim/detector/liqField 450 volt/cm

#	Update geometry
/LUXSim/detector/update


#	Select the record levels of the volumes. The default record level is 0.

#	These next commands demonstrate how you can set the record level of 
#	all components with the same base name in one command, but then set the
#	record level of individual components on a finer scale.
#/LUXSim/detector/recordLevel Top_PMT_Window 1
#/LUXSim/detector/recordLevel Top_PMT_Window_2 2

#/LUXSim/detector/recordLevel Bottom_PMT_Window 1
#/LUXSim/detector/recordLevel Bottom_PMT_Window_3 3

/LUXSim/detector/recordLevel LiquidXenon 1
/LUXSim/detector/recordLevel GasXenon 1
#/LUXSim/detector/recordLevel HDPEHolder 1
#/LUXSim/detector/recordLevel PTFESheets 1
#/LUXSim/detector/recordLevel RadShield 1 
#/LUXSim/detector/recordLevel RadDome 1 
#/LUXSim/detector/recordLevel PMTHolder 2
#/LUXSim/detector/recordLevel BottomPMTHolder 3

#/LUXSim/detector/recordLevelOptPhot LiquidXenon 2
#/LUXSim/detector/recordLevelOptPhot PMT_Window 2

#	Set the event generation.

#	This can be used in place of the regular the event generators. Be sure you
#	know what you're doing if you're going to use commands like these.
/gps/particle gamma
/gps/energy 122 keV
/gps/position 0 0 0 cm
/gps/ang/type iso

#	This next set of commands sets the activity of the various components. As
#	with the record level commands, you can set activities of many components
#	with a single command, and then you can fine-tune the activity of individual
#	components
#/LUXSim/source/set PMT_Window Th232 10 Bq
#/LUXSim/source/set Top_PMT_Window_3 AmBe 100 Bq
#/LUXSim/source/set BottomPMTHolder Th232 1 Bq
#/LUXSim/source/set PMT_Window U238 5 Bq
#/LUXSim/source/set PMT_Window Rn222 10 Bq
#/LUXSim/source/set LiquidXenon ScintPhotons 1 Bq
#/LUXSim/source/set LithiumTarget pLithium 10000 Bq

#	Use this line to turn on or off optical photons
/LUXSim/physicsList/useOpticalProcesses false

#	Use this line instead of "/run/beamOn", as there is internal bookkeeping
#	that needs to occur before the run is started.
/LUXSim/beamOn 10
